Feat: rebrand web wallet to flash
lnflash/web-wallet pull request #2
Opened 2023-10-07 18:49 UTC by YLeight

Resolves: #1

2023-10-08 15:46 UTC, islandbitcoin commented
colors look good - the footer still says "Powered by Galoy" can we change that to "Powered by Flash" with the URL being https://getflash.io

2023-10-08 16:16 UTC, islandbitcoin requested changes
Small change needed then LGTM

2023-10-08 16:16 UTC, islandbitcoin commented on src/components/__snapshots__/root.spec.tsx.snap
> +          href="https://flash.io/"
getflash.io

2023-10-10 11:38 UTC, YLeight commented on src/components/__snapshots__/root.spec.tsx.snap
> +          href="https://flash.io/"
Done

2023-10-10 11:54 UTC, islandbitcoin approved these changes
LTGM

2023-10-10 11:55 UTC, merged